version: 2
machine:
    services:
        - docker
dependencies:
    override:
        - sudo add-apt-repository ppa:masterminds/glide -y
        - sudo apt-get update
        - sudo apt-get install glide -y
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/metrue/fx

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Dep
          command: |
              go get github.com/golang/dep
              cd $GOPATH/src/github.com/golang/dep
              go install ./...

      - run:
          name: Build and Install
          command: |
              make install-deps
              make build

      - run:
          name: Unit Test
          command: |
              ./bin/coverage.sh
              bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

      - run:
          name: Integration Test
          command: |
              ./bin/test_cli.sh

deployment:
    production:
    branch: master
    commands:
        - echo "Not Ready Yet"
